substitutions:
  name: "air-quality-dzuris-home"
  area: "#Living Room"
  project_name: "Dzuriš Home.ESPHome IKEA VINDRIKTNING"
  device_description: "ESPHome IKEA VINDRIKTNING by Dzuriš Home"
  project_version: "1.0"

#OTA Remote
dashboard_import: #Dont Delete when you want OTA Remote if you dont want OTA Remote Delete (dashboard_import and below that)
  package_import_url: github://DzurisHome/ESPHome-IKEA-VINDRIKTNING/ESPHomeConfig/dzuris-home-esphome-config-ikea-vindriktning-esp8266-mq-135.yaml
  import_full_config: false

#ESPHome Core
esphome:
  name: "${name}"
  area: "${area}"
  name_add_mac_suffix: true #Delete (name_add_mac_suffix) when you Renamed Device
  project:
    name: "${project_name}"
    version: "${project_version}"

esp8266:
  board: d1_mini

#Logger
logger:

#WiFi
wifi:
  ssid: #SSID or !secret wifi_ssid
  password: #Password or !secret wifi_password

  manual_ip: #If you dont want set manual IPs Delete (manual_ip and uder)
    static_ip: #Air Quality Device IP
    gateway: #Router IP
    subnet: #Router Subnet IP

  ap:
    ssid: "Air Quality Dzuriš Home AP"
    password: #Acess Point password or !secret ap_password

captive_portal:

#Web Server
web_server: #If you dont want Web Server Delete (web_server and below that) 
  port: 80
  auth:
    username: #Username or !secret web_server_username
    password: #Password or !secret web_server_password

#OTA
ota:
  safe_mode: true
  password: #Password or !secret ota_password

#MQTT
mqtt: #If you dont have or want MQTT Broker Delete (mqtt and below that)
  broker: #Broekr or !secret mqtt_broker_ip_address
  username: #Username or !secret mqtt_broker_username
  password: #Password or !secret mqtt_broker_password
  client_id: "Air Quality Dzuriš Home"
  discovery: false #If you chnnge to true Home Assistant dont discovery device only from MQTT Integration
  topic_prefix: "Air Quality Dzuriš Home"

#ESPHome API
api: #Dont Delete when you want OTA Remote if you dont want ESPHome API and OTA Remote Delete (api and below that)
  encryption:
    key: #Key or !secret api_encryption_key

#Home Assistant Time
time: #Home Assistant time something other or Delete (time and below that)
  - platform: homeassistant
    id: homeassistant_time

#Device Required
uart:
  rx_pin: D2
  baud_rate: 9600

#Device
binary_sensor:
  - platform: gpio
    pin:
      number: D4
      inverted: true
    name: "Living Room Air Quality Fan"

sensor:
  - platform: pm1006
    pm_2_5:
      id: particulate_matter_2_5
      name: "Living Room Particulate Matter 2.5µm"

  - platform: adc
    pin: A0
    id: carbon_monoxide
    name: "Living Room Carbon Monoxide"
    icon: mdi:molecule-co
    update_interval: 30s
    unit_of_measurement: "ppm"
    device_class: "carbon_monoxide"
    state_class: "measurement"
    filters:
        - lambda: return (x * 1024/5); 

#Diagnostic
  - platform: wifi_signal
    name: "Living Room Air Quality RSSI"
    update_interval: 1min
    unit_of_measurement: "dBm"
    device_class: "signal_strength"
    state_class: "measurement"
    entity_category: "diagnostic"

  - platform: uptime
    id: uptime_seconds
    name: "Uptime Seconds"
    icon: mdi:clock-time-four-outline
    update_interval: 1min
    internal: true
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_sensor
            state: !lambda |-
              int seconds = round(id(uptime_seconds).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();

#Sensor
text_sensor:
  - platform: template
    name: "Living Room Air Quality Color"
    icon: mdi:led-strip
    update_interval: 30s
    lambda: |-
      if (id(particulate_matter_2_5).state <= 35.0) {
        return {"Green"};
      } else if (id(particulate_matter_2_5).state > 35.0 && id(particulate_matter_2_5).state <= 85.0) {
        return {"Orange"};
      } else {
        return {"Red"};
      }

  - platform: template
    name: "Living Room Particulate Matter 2.5µm Air Quality"
    icon: mdi:emoticon
    update_interval: 30s
    lambda: |-
      if (id(particulate_matter_2_5).state <= 12.0) {
        return {"Excellent"};
      } else if (id(particulate_matter_2_5).state > 12.0 && id(particulate_matter_2_5).state <= 35.0) {
        return {"Good"};
      } else if (id(particulate_matter_2_5).state > 35.0 && id(particulate_matter_2_5).state <= 55.0) {
        return {"Moderate"};
      } else if (id(particulate_matter_2_5).state > 55.0 && id(particulate_matter_2_5).state <= 150.0) {
        return {"Unhealthy for Sensitive Groups"};
      } else if (id(particulate_matter_2_5).state > 150.0 && id(particulate_matter_2_5).state <= 250.0) {
        return {"Unhealthy"};
      } else if (id(particulate_matter_2_5).state > 250.0 && id(particulate_matter_2_5).state <= 350.0) {
        return {"Very Unhealthy"};
      } else {
        return {"Hazardous"};
      }

  - platform: template
    name: "Living Room Carbon Monoxide Air Quality"
    icon: mdi:emoticon
    update_interval: 30s
    lambda: |-
      if (id(carbon_monoxide).state <= 50.0) {
        return {"Excellent"};
      } else if (id(carbon_monoxide).state > 50.0 && id(carbon_monoxide).state <= 100.0) {
        return {"Good"};
      } else if (id(carbon_monoxide).state > 100.0 && id(carbon_monoxide).state <= 200.0) {
        return {"Moderate"};
      } else if (id(carbon_monoxide).state > 200.0 && id(carbon_monoxide).state <= 400.0) {
        return {"Unhealthy for Sensitive Groups"};
      } else if (id(carbon_monoxide).state > 400.0 && id(carbon_monoxide).state <= 800.0) {
        return {"Unhealthy"};
      } else {
        return {"Very Unhealthy"};
      }

#Diagnostic
  - platform: template
    id: uptime_sensor
    name: "Living Room Air Quality Uptime"
    icon: mdi:clock-time-four-outline
    entity_category: "diagnostic"

#Configuration
button:
  - platform: restart
    name: "Living Room Air Quality Restart"
